title: [Personal Documentation]
description: [General Documention For Technical Related Matters]
theme: jekyll-theme-cayman
baseurl: /personal-documentation
collections:
  documentation_techniques:
    output: true
  databases:
    output: true
  webop_docs:
    output: true