title: [Personal Documentation]
description: [General Documention For Technical Related Matters]
theme: jekyll-theme-cayman
baseurl: /personal-documentation
collections:
  documentationtechs:
    output: true
  databases:
    output: true